insert into news (link, img, tag, title, body, author, date) values ('https://vs.com.br/artigo/hackers-de-apex-legends-e-csgo-tem-dados-pessoais-roubados', 'https://images.vs.com.br/smartcrop?compression=8&height=180&quality=65&url=https%3A%2F%2Fstorage.googleapis.com%2Fwebedia-temp%2F1566312560037-csgo-1.jpg&width=320', 'CS:GO', 'Hackers de Apex Legends e CS:GO têm dados pessoais roubados', 'O malware continua sendo utilizado na internet', 'Beatriz Coutinho', '20 Agosto 2019');
insert into news (link, img, tag, title, body, author, date) values ('https://vs.com.br/artigo/lol-atualizacao-917-trara-buffs-para-pantheon-yasuo-galio-e-ryze', 'https://images.vs.com.br/smartcrop?compression=8&height=180&quality=65&url=https%3A%2F%2Fstorage.googleapis.com%2Fwebedia-temp%2F1566311256523-lol-pantheon-yasuo.png&width=320', 'League of Legends', 'LoL: Atualização 9.17 trará buffs para Pantheon, Yasuo, Galio e Ryze', 'Aurelion Sol, Kayle e Neeko também estão na lista de mudanças', 'Lucas Hagui', '20 Agosto 2019');
insert into news (link, img, tag, title, body, author, date) values ('https://vs.com.br/artigo/fornite-brasileiros-dominam-top-8-regional-na-estreia-da-championship-series', 'https://images.vs.com.br/smartcrop?compression=8&height=180&quality=65&url=https%3A%2F%2Fstorage.googleapis.com%2Fwebedia-temp%2F1566307615680-fortnite-trios.jpg&width=320', 'Fortnite', 'Fornite: Brasileiros dominam top 8 regional na estreia do Championship Series', 'Cinco trios com brasileiros já estão classificados para a Fase 2 ', 'Helena Nogueira', '20 Agosto 2019');
insert into news (link, img, tag, title, body, author, date) values ('https://vs.com.br/artigo/call-of-duty-one-academy-recebe-torneio-sul-americano-com-premiacao-de-rdollar-4-mil', 'https://images.vs.com.br/smartcrop?compression=8&height=180&quality=65&url=https%3A%2F%2Fstorage.googleapis.com%2Fwebedia-temp%2F1566308490965-apps52687647591518328570194c47f709-d704-42d5-bc21-4a00a839e42b.jpg&width=320', 'Call of Duty', 'Call of Duty: One Academy recebe torneio sul-americano com premiação de R$ 4 mil', 'Disputa acontecerá em outubro', 'Beatriz Coutinho', '20 Agosto 2019');
insert into news (link, img, tag, title, body, author, date) values ('https://vs.com.br/artigo/csgo-gaules-tera-direitos-de-imagem-do-starladder-berlin-major-2019', 'https://images.vs.com.br/smartcrop?compression=8&height=180&quality=65&url=https%3A%2F%2Fstorage.googleapis.com%2Fwebedia-temp%2F1566308361972-gaules-copia.jpg&width=320', 'CS:GO', 'CS:GO: Gaules terá direitos de imagem do Starladder Berlin Major 2019', 'Além das partidas, a transmissão também terá imagens de jogadores, palco e mais', 'Jairo Junior', '20 Agosto 2019');
insert into news (link, img, tag, title, body, author, date) values ('https://vs.com.br/artigo/overwatch-lowkey-e-campea-da-2a-temporada-da-contenders-2019', 'https://images.vs.com.br/smartcrop?compression=8&height=180&quality=65&url=https%3A%2F%2Fstorage.googleapis.com%2Fwebedia-temp%2F1566302912728-dmicstau8aaoew2.jpg&width=320', 'Overwatch', 'Overwatch: Lowkey é campeã da 2ª temporada da Contenders 2019', 'Equipe conquistou o bicampeonato do torneio', 'Beatriz Coutinho', '20 Agosto 2019');
insert into news (link, img, tag, title, body, author, date) values ('https://vs.com.br/artigo/csgo-camyy-e-a-nova-jogadora-da-team-one', 'https://images.vs.com.br/smartcrop?compression=8&height=180&quality=65&url=https%3A%2F%2Fstorage.googleapis.com%2Fwebedia-temp%2F1566227805976-camyy-keyd-2.jpg&width=320', 'CS:GO', 'CS:GO: Camyy é a nova jogadora da Team One', 'Jogadora estava sem equipe desde que deixou a paiN Gaming', 'Jairo Junior', '19 Agosto 2019');
insert into news (link, img, tag, title, body, author, date) values ('https://vs.com.br/ultimas', 'https://images.vs.com.br/smartcrop?compression=8&height=180&quality=65&url=https%3A%2F%2Fstorage.googleapis.com%2Fwebedia-temp%2F1566227805976-camyy-keyd-2.jpg&width=320', 'CS:GO', 'CS:GO: Camyy é a nova jogadora da Team One', 'Jogadora estava sem equipe desde que deixou a paiN Gaming', 'Jairo Junior', '19 Agosto 2019');

